version: '3.3'

services:
  figma-context-mcp:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      # Uncomment and set your Figma API key for production deployment
      # - FIGMA_API_KEY=your_figma_api_key
    volumes:
      # Mount a volume for logs
      - ./logs:/app/logs
    restart: unless-stopped